apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: driving-school
type: Opaque
stringData:
  JWT_SECRET: mySecretKeyForJWTTokenGenerationAndValidationInDrivingSchoolAuthService
  JWT_EXPIRATION_MS: "86400000"
