apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-credentials
  namespace: driving-school
type: Opaque
stringData:
  POSTGRES_DB: drivingschool_auth
  POSTGRES_USER: authuser
  POSTGRES_PASSWORD: authpass123
